CREATE DATABASE IF NOT EXISTS memoryverse_html_db;
USE memoryverse_html_db;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),email VARCHAR(180) UNIQUE,password_hash VARCHAR(255),language VARCHAR(10) DEFAULT 'en',appearance VARCHAR(10) DEFAULT 'dark');
CREATE TABLE IF NOT EXISTS events(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,title VARCHAR(220),receiver_name VARCHAR(140),event_type VARCHAR(50),subtitle VARCHAR(255),final_message TEXT,language VARCHAR(10),appearance VARCHAR(10),slug VARCHAR(160) UNIQUE,status VARCHAR(40) DEFAULT 'draft',qr_url VARCHAR(255));
CREATE TABLE IF NOT EXISTS memories(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT,title VARCHAR(220),description TEXT,emotion_tag VARCHAR(60),media_url VARCHAR(255),media_type VARCHAR(30));
CREATE TABLE IF NOT EXISTS wishes(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT,name VARCHAR(120),message TEXT);
CREATE TABLE IF NOT EXISTS reactions(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT,reaction VARCHAR(40));
